### ISSUE TITLE
Not starting on 10.8.3

### ISSUE THREAD

**Issue by acgourley** [orta/SpeedS-ver#1]
It worked at first, then I switched away from the preview (either clicking on another screen saver or leaving the settings app) and the settings app crashed. At this point, restarting the screen saver does not work, the screen is simply blank. I've re-installed the screen saver, and even built a new version in x-code - no luck. Running the bootstrap directly works, so it's something about the screen saver not starting up... perhaps it didn't clean up properly after the crash and cannot recover. Rebooting does not help. 

Great concept though, I'm excited to see it progress.

**Comment by orta** [comment]
Thanks @acgourley - I'll have a think about it.

**Comment by orta** [comment]
Could be that the QT framework was still running on its own process, and trying to reload would attempt the same instance. Unsure how I can protect against that atm.

**Comment by acgourley** [comment]
What would the process be named? I can attempt to check for it and kill. I also walked away and had it working when I returned, but most of the time it's blank. So the behavior is currently spotty.

**Comment by acgourley** [comment]
Sorry for all the noise here. This time I started it, it was blank for a minute, then it loaded up a video download splash. Upon trying to play it crashed and closed the screensaver.

**Comment by orta** [comment]
Yes, usually with the app name:
![screen shot 2013-05-12 at 23 50 02](https://f.cloud.github.com/assets/49038/493590/53de74ea-bb56-11e2-85ed-17a5aada1acc.png)

I've just added some fixes which are in the master, but not zipped yet that might fix this

**Comment by acgourley** [comment]
Awesome. Okay I've built from master, deleted the old one, and installed. Let me observe what's going on for a day or two and i'll report back. I'll keep a look out for a runaway process. Let me know if you have new changes you want me to try.

**Comment by orta** [comment]
With the rest of the oddities, try uninstalling and grabbing the [new zip](https://raw.github.com/orta/GamesScreenSaver/master/web/GamesScreensaver.saver.zip) and giving it a go

**Comment by orta** [comment]
Thanks! ( you probably won't need the new zip if you've grabbed form master. )

**Comment by acgourley** [comment]
Odd behavior continues. First of all when it starts up from the OS timer, it will always play a few frames of video then turn off. This will usually leave an orphaned QT process, but killing that process does nothing to make things work better in the future. 

Second of all, I can manually launch the screen saver preview from Settings and it usually works. Now that I have some videos downloaded I don't seem to get that black screen behavior, I get one of the videos.

**Comment by orta** [comment]
Odd, I've started some work on having streaming support and in doing so I've been moving the video player from QuickTime into AVFoundation ( which was introduced in 10.7 ) so we'll see if that makes any difference.

**Comment by orta** [comment]
I've moved the screensaver's video to AVFoundation, if you're still compiling yourself you can pull from master and test that. I may make a proper release later tonight, hard to tell.

**Comment by acgourley** [comment]
Still has some other erratic behavior, for example now the video is frozen on the first frame of a video. The black screen issue is gone so I'll go ahead and close this issue as it shouldn't be a thread documenting my quest to get a stable game screen saver. Thanks again, keep at it and i'll check in later for the next release and test it more then.

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
BTW: what hardware are you running this on?

**Comment by acgourley** [comment]
2009 iMac
