### ISSUE TITLE
Screensaver makes "screensaver settings" hang.

### ISSUE THREAD

**Issue by emilpriver** [orta/SpeedS-ver#9]
Downloaded the screensaver, installed it and activate it. After I chose the screensaver was the screen settings blank. Nothing on it, needed to exit settings and start and fast change to another screensaver to be able to edit inside the screensaver settings page.

**Comment by Trychlik** [comment]
its not compatible with 10.14 :(

**Comment by emilpriver** [comment]
:(

**Comment by emilpriver** [comment]
:(

**Comment by ghost** [comment]
i'm having the same problem...
really hope it will be updated/fixed soon
